### ISSUE TITLE
Picom method no longer works

### ISSUE THREAD

**Issue by matteqa** [bubbleguuum/toggle-monitor-grayscale#2]
Picom has changed the way that shaders are handled breaking this script.

It can be fixed by adding --legacy-backends to line 76 however this solution is deprecated.

**Comment by bubbleguuum** [comment]
Yup, I noticed this recently. 
The proper fix would be to put the shader into a file and rewritten to  new shader syntax taken by `--window-shader-fg`

**Comment by bubbleguuum** [comment]
Fixed with recent commit. The script can now handle old and recent `picom`, using `--window-shader-fg` with the later.
