### ISSUE TITLE
Legacy Backend 'glx' Error

### ISSUE THREAD

**Issue by enzv** [bubbleguuum/toggle-monitor-grayscale#5]
Thank you for the script. It likely aids many seeking peace during their tasks. Here's my xinitrc, providing context for my environment:

```sh
#!/usr/bin/env bash
setxkbmap latam
picom &
gentoo-pipewire-launcher &
exec dbus-run-session dwm
```

I haven't thoroughly read the script, but I believe it's functional. The script requires picom to be running; it then terminates it and, through a series of lines of code and conditions, establishes the steps necessary to achieve the grayscale effect. I will execute the script and provide the steps for  reproducibility.

```sh
cd $(mktemp -d)
git clone --depth=1 https://github.com/bubbleguuum/toggle-monitor-grayscale.git .
git rev-parse HEAD
# a83735ce6208bc86d355ea9d9eeb828045b338a1
sh toggle-monitor-grayscale.sh
# picom: set to grayscale
```

The script seems nonfunctional as I'm not observing grayscale effects. Removing the redirection to the null device, I've discovered some intriguing elements:

```diff
diff --git a/toggle-monitor-grayscale.sh b/toggle-monitor-grayscale.sh
index 979f017..fec4037 100755
--- a/toggle-monitor-grayscale.sh
+++ b/toggle-monitor-grayscale.sh
@@ -104 +104 @@ EOF
-           $compositor $* -b --backend glx --window-shader-fg ${tmpfile} 2> /dev/null
+           $compositor $* -b --backend glx --window-shader-fg ${tmpfile}
@@ -109 +109 @@ EOF
-           $compositor $* -b --backend glx --glx-fshader-win "${shader}" 2> /dev/null
+           $compositor $* -b --backend glx --glx-fshader-win "${shader}"
```

```sh
sh toggle-monitor-grayscale.sh
# [ 04/16/24 23:04:42.839 get_cfg ERROR ] Backend "glx" is only available as part of the legacy backends.
# [ 04/16/24 23:04:42.839 session_init FATAL ERROR ] Failed to get configuration, usually mean you have specified invalid options.
# [ 04/16/24 23:04:42.839 main FATAL ERROR ] Failed to create new session.
# picom: set to grayscale
```

Any thoughts? I'm not an expert on picom or compositors; it's my first time using one. I'm hoping to at least receive some hints here. Thank you!

**Comment by enzv** [comment]
Here's the version of picom I'm using
```sh
picom --version
# v11
```

**Comment by enzv** [comment]
CC @bubbleguuum

**Comment by bubbleguuum** [comment]
Hi,

Looking at picom source code, this error message happens only if picom was compiled without OpenGL support (that is, with `CONFIG_OPENGL` undefined) which the script does not check to produce a more meaningful error message. This is rather unusual. Did you compile picom yourself ? If not, what is your distro ?

**Comment by enzv** [comment]
Apologies, I missed a crucial step. Yesterday, I checked for an OpenGL flag but didn't see it, probably because I was too tired. I'm using Gentoo Linux. Feeling a bit silly about the oversight. Anyway, for others on the distro, just:

```bash
sudo su -
USE=opengl emerge x11-misc/picom
```

**Comment by enzv** [comment]
Thank you @bubbleguuum.
